src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 100)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Name',
                ],
            ])
            ->add('date', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Date and Time',
                ],
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Description',
                ],
            ])
            ->add('photo', TextType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Photo URL',
                ],
            ])
            ->add('capacity', IntegerType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Capacity',
                ],
            ])
            ->add('email', EmailType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Email',
                ],
            ])
            ->add('phone_number', TelType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Phone Number',
                ],
            ])
            ->add('address', TextType::class, [
                'attr' => [
                    'class' => 'form-control my-3',
                    'placeholder' => 'Address',
                ],
            ])
            ->add('type', ChoiceType::class, [
                'label' => false,
                'attr' => [
                    'class' => 'form-control my-3',
                ],
                'choices'  => [
                    'Music' => 'music',
                    'Sport' => 'sport',
                    'Movie' => 'movie',
                    'Theater' => 'theater',
                ],
                'placeholder' => 'Select Type',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Form\EventsType;
use App\Repository\EventsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/')]
class EventsController extends AbstractController
{
    #[Route('/', name: 'app_events_index', methods: ['GET'])]
    public function index(Request $request, EventsRepository $eventsRepository): Response
    {

        $type = $request->query->get('type');
        $events = $eventsRepository->findByType($type);

        return $this->render('events/index.html.twig', [
            'events' => $events,
            'selectedType' => $type,
        ]);
    }

    #[Route('/new', name: 'app_events_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Events();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_show', methods: ['GET'])]
    public function show(Events $event): Response
    {
        return $this->render('events/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_events_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_delete', methods: ['POST'])]
    public function delete(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/events/_delete_form.html.twig
<form method="post" action="{{ path('app_events_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this event?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

templates/events/_form.html.twig
{% block body %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card shadow-sm">
                <div class="card-body">

                    {{ form_start(form) }}

                    <div class="mb-3">
                        {{ form_row(form.name, { 'attr': {'class': 'form-control', 'placeholder': 'Name'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.date, { 'attr': {'class': 'form-control', 'placeholder': 'Date and Time'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.description, { 'attr': {'class': 'form-control', 'placeholder': 'Description'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.photo, { 'attr': {'class': 'form-control', 'placeholder': 'Photo URL or Path'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.capacity, { 'attr': {'class': 'form-control', 'placeholder': 'Capacity'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Email'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.phone_number, { 'attr': {'class': 'form-control', 'placeholder': 'Phone Number'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.address, { 'attr': {'class': 'form-control', 'placeholder': 'Address'} }) }}
                    </div>

                    <div class="mb-3">
                        {{ form_row(form.type, { 'attr': {'class': 'form-control'} }) }}
                    </div>

                    <div class="text-center">
                        <button class="btn btn-primary btn-lg w-100">{{ button_label|default('Save') }}</button>
                    </div>

                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
<div class="container my-5">
    <h1 class="text-center mb-4">Edit Event</h1>

    <div class="row">
        <div class="col-md-8 offset-md-2">
            {{ include('events/_form.html.twig', {'button_label': 'Update'}) }}
            
            <div class="d-flex justify-content-between align-items-center mt-4">
                <a href="{{ path('app_events_index') }}" class="btn btn-info text-light">Back to List</a>
                {{ include('events/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events Index{% endblock %}
{% block stylesheets %}
<style>
.form-select {
    border-radius: 0.375rem;
    box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.125);
}
</style>
        {% endblock %}
{% block body %}
<div class="container my-5">
    <h1 class="text-center mb-4">Upcoming Events</h1>

    <div class="mb-3 d-flex justify-content-between">
        <a href="{{ path('app_events_new') }}" class="btn btn-success btn-lg">Create New Event</a>
        
        
        <form method="get" action="{{ path('app_events_index') }}" class="d-flex align-items-center mb-4">
    <div class="input-group me-3">
        <select name="type" class="form-select" aria-label="Filter by type">
            <option value="">Select Type</option>
            <option value="music" {% if app.request.query.get('type') == 'music' %}selected{% endif %}>Music</option>
            <option value="sport" {% if app.request.query.get('type') == 'sport' %}selected{% endif %}>Sport</option>
            <option value="movie" {% if app.request.query.get('type') == 'movie' %}selected{% endif %}>Movie</option>
            <option value="theater" {% if app.request.query.get('type') == 'theater' %}selected{% endif %}>Theater</option>
        </select>
    </div>
    <button type="submit" class="btn btn-info btn-sm text-light">Filter Events</button>
</form>
    </div>

    <div class="row g-4">
        {% for event in events %}
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 shadow-sm">
                    <img src="{{ event.photo }}" class="card-img-top" alt="Event Photo" style="object-fit: cover; height: 200px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ event.date ? event.date|date('Y-m-d H:i:s') : 'N/A' }}</h6>
                        <p class="card-text">{{ event.description|slice(0, 100) ~ (event.description|length > 100 ? '...' : '') }}</p>
                    </div>
                    <div class="card-footer text-muted">
                        <p><strong>Capacity:</strong> {{ event.capacity }}</p>
                        <p><strong>Email:</strong> {{ event.email }}</p>
                        <p><strong>Phone:</strong> {{ event.phoneNumber }}</p>
                        <p><strong>Address:</strong> {{ event.address }}</p>
                        <p><strong>Type:</strong> {{ event.type }}</p>
                        <div class="d-flex justify-content-between">
                            <a href="{{ path('app_events_show', {'id': event.id}) }}" class="btn btn-info btn-sm">Show</a>
                            <a href="{{ path('app_events_edit', {'id': event.id}) }}" class="btn btn-warning btn-sm">Edit</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="col-12 text-center">
                <p>No records found</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/events/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Events{% endblock %}

{% block body %}
    <h1>Create new Events</h1>

    {{ include('events/_form.html.twig') }}

    <a href="{{ path('app_events_index') }}">back to list</a>
{% endblock %}

templates/events/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event Details{% endblock %}

{% block body %}
<div class="container my-5">
    <h1 class="text-center mb-4">Event Details</h1>

    <div class="row mb-4">
        <div class="col-md-6">
            <img src="{{ event.photo }}" class="img-fluid rounded" alt="Event Photo" style="object-fit: cover; height: 400px;">
        </div>
        <div class="col-md-6">
            <h2>{{ event.name }}</h2>
            <p class="text-muted"><strong>Date:</strong> {{ event.date ? event.date|date('F j, Y, g:i a') : 'N/A' }}</p>
            <p><strong>Description:</strong> {{ event.description }}</p>
            <ul class="list-unstyled">
                <li><strong>Capacity:</strong> {{ event.capacity }}</li>
                <li><strong>Email:</strong> {{ event.email }}</li>
                <li><strong>Phone Number:</strong> {{ event.phoneNumber }}</li>
                <li><strong>Address:</strong> {{ event.address }}</li>
                <li><strong>Type:</strong> {{ event.type }}</li>
            </ul>
        </div>
    </div>

    <div class="text-center">
        <a href="{{ path('app_events_index') }}" class="btn btn-primary">Back to List</a>
        <a href="{{ path('app_events_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
        {{ include('events/_delete_form.html.twig') }}
    </div>
</div>
{% endblock %}